In [1]:
import torch
from torch import nn
import torch.nn.functional as F

import numpy as np

import matplotlib.pyplot as plt

import torch

Attention calculation

1/ Autoregressive masking  
With the knowledge of previous frames, attention should be lessen in the current frame  
2/ 

In [2]:
mask = torch.triu(torch.ones(4, 4))
mask

tensor([[1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.]])

In [3]:
rand = torch.rand((4, 4))
rand

tensor([[0.7986, 0.6089, 0.9237, 0.6273],
        [0.2886, 0.1342, 0.6441, 0.4083],
        [0.0273, 0.0573, 0.0475, 0.0548],
        [0.7438, 0.4991, 0.3085, 0.2498]])

In [4]:
rand.masked_fill(mask.to(torch.bool), -1e-4)

tensor([[-1.0000e-04, -1.0000e-04, -1.0000e-04, -1.0000e-04],
        [ 2.8856e-01, -1.0000e-04, -1.0000e-04, -1.0000e-04],
        [ 2.7349e-02,  5.7350e-02, -1.0000e-04, -1.0000e-04],
        [ 7.4383e-01,  4.9906e-01,  3.0855e-01, -1.0000e-04]])

In [5]:
(rand.masked_fill(mask.to(torch.bool), -1e4)).softmax(-1)

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [1.0000, 0.0000, 0.0000, 0.0000],
        [0.4925, 0.5075, 0.0000, 0.0000],
        [0.4115, 0.3222, 0.2663, 0.0000]])